"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-05 11:38:09.912553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('prompt_snapshot_json', sa.Text(), nullable=False),
    sa.Column('staged_results_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=80), nullable=True),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_feedback_index_card_id'), 'feedback_index', ['card_id'], unique=False)
    op.create_table('profile_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_audio_json', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.String(length=40), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_facts_subject_id'), 'profile_facts', ['subject_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'version', name='uq_prompt_scene_version')
    )
    op.create_table('provider_metadata',
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('last_validated_at', sa.String(length=40), nullable=True),
    sa.Column('last_validation_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_validation_error_message', sa.Text(), nullable=True),
    sa.Column('default_model_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index('uq_provider_single_active', 'provider_metadata', ['active'], unique=True, sqlite_where=sa.text('active IS 1'))
    op.create_table('temp_file_manifest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('cleanup_status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_temp_file_manifest_task_uuid'), 'temp_file_manifest', ['task_uuid'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.String(length=40), nullable=False),
    sa.Column('natural_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_batches_uploaded_at'), 'batches', ['uploaded_at'], unique=False)
    op.create_table('job_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=8), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('temporary_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sha256', name='uq_job_file_hash')
    )
    op.create_index(op.f('ix_job_files_job_id'), 'job_files', ['job_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_batch_id'), 'cards', ['batch_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_file_id', sa.String(length=36), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('words_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_file_id'], ['job_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_file_id', 'segment_index', name='uq_transcript_segment')
    )
    op.create_index(op.f('ix_transcripts_job_file_id'), 'transcripts', ['job_file_id'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_messages_card_id'), 'qa_messages', ['card_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_card_id', sa.String(length=80), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due_at', sa.String(length=40), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_batch_id'), 'todos', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_batch_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_qa_messages_card_id'), table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index(op.f('ix_transcripts_job_file_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_cards_batch_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_job_files_job_id'), table_name='job_files')
    op.drop_table('job_files')
    op.drop_index(op.f('ix_batches_uploaded_at'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_temp_file_manifest_task_uuid'), table_name='temp_file_manifest')
    op.drop_table('temp_file_manifest')
    op.drop_index('uq_provider_single_active', table_name='provider_metadata', sqlite_where=sa.text('active IS 1'))
    op.drop_table('provider_metadata')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_profile_facts_subject_id'), table_name='profile_facts')
    op.drop_table('profile_facts')
    op.drop_index(op.f('ix_feedback_index_card_id'), table_name='feedback_index')
    op.drop_table('feedback_index')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
